
project:
  type: website
  output-dir: docs

website:
  title: "RTVS Geography Extras"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: chsa.qmd
        text: CHSA

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
    code-link: true

editor: source

editor_options: 
  chunk_output_type: console
