project:
  type: website
  output-dir: docs

website:
  title: "RTVS Geography Extras"
  navbar:
    left:
      - href: index.qmd
        text: Main

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

